# Define the starting IP address
ip_base = "192.168.42."

Vagrant.configure("2") do |config|
  # Define VM: web01 with Ubuntu 20.04
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "#{ip_base}10"
  end

  # Define VM: web02 with Ubuntu 20.04
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "#{ip_base}11"
  end

  # Define VM: db01 with CentOS 7
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "#{ip_base}12"
    db01.vm.provision "shell", inline: <<-SHELL
        sudo yum install -y mariadb-server
        sudo systemctl start mariadb
        sudo systemctl enable mariadb
    SHELL
  end
end